name: Publish container

on:
  workflow_dispatch:
  push:
    branches: [ main, "release/**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: project-unisonOS/unison-platform/.github/workflows/reusable-build.yml@master
    with:
      image_name: unison-consent
      domain: consent
      service_port: "7072"
    secrets: inherit
